name: CursorConnector
options:
  bundleIdPrefix: com.cursorconnector
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  CursorConnector:
    type: application
    platform: iOS
    sources:
      - CursorConnector
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: CursorConnector/Info.plist
      properties:
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
